var num1 = 1;
var num2 = -2;
var num3 = 3.4;
var num4 = 4.8;
var str1 = "hi";
var str2 = "hi2";
var str3 = "hi3";
var tru = true;
var fal = false;
var und = undefined;
console.log("The first number: " + num1);
console.log("The second number: " + num2);
console.log("The third number: " + num3);
console.log("The fourth number: " + num4);
console.log("The first string: " + str1);
console.log("The second string: " + str2);
console.log("The third string: " + str3);
console.log("The true boolean: " + tru);
console.log("The false boolean: " + fal);
console.log("The undefined data type: " + und);